// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.4

package types

type LoginRequest struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type LoginResponse struct {
	Token string       `json:"token"`
	User  UserResponse `json:"user"`
}

type UserRequest struct {
	Id int64 `path:"id"`
}

type UserResponse struct {
	Id   int64  `json:"id"`
	Name string `json:"name"`
	Age  int32  `json:"age"`
}
